#
#                 - Mellanox Confidential and Proprietary -
#
# Copyright (C) January 2010, Mellanox Technologies Ltd.  ALL RIGHTS RESERVED.
#
# Except as specifically permitted herein, no portion of the information,
# including but not limited to object code and source code, may be reproduced,
# modified, distributed, republished or otherwise exploited in any form or by
# any means for any purpose without the prior written permission of Mellanox
# Technologies Ltd. Use of software subject to the terms and conditions
# detailed in the file "LICENSE.txt".
#
#
EXTRA_CFLAGS += $(SXD_KERNEL_EXTRA_CFLAGS)
KBUILD_EXTRA_SYMBOLS := $(EXTRA_SYMVERS)
obj-m += sx_emad_dump.o

sx_emad_dump-objs := sx_emad_dump_main.o

