/*
 * Copyright (c) 2018-2023 NVIDIA CORPORATION & AFFILIATES. ALL RIGHTS RESERVED.
 *
 * This software product is a proprietary product of Nvidia Corporation and its affiliates
 * (the "Company") and all right, title, and interest in and to the software
 * product, including all associated intellectual property rights, are and
 * shall remain exclusively with the Company.
 *
 * This software product is governed by the End User License Agreement
 * provided with the software product.
 */


/*
 * THIS FILE IS AUTO GENERATED.
 * DO NOT MAKE ANY CHANGES!
 * They will be erased with next update.
 *
 */

CTRL_CMD_ACCESS_REG_HGCR, /**< Run access register HGCR command */
CTRL_CMD_ACCESS_REG_HMON, /**< Run access register HMON command */
CTRL_CMD_ACCESS_REG_HCOT, /**< Run access register HCOT command */
CTRL_CMD_ACCESS_REG_HRDQT, /**< Run access register HRDQT command */
CTRL_CMD_ACCESS_REG_HTACG, /**< Run access register HTACG command */
CTRL_CMD_ACCESS_REG_HETT, /**< Run access register HETT command */
CTRL_CMD_ACCESS_REG_HCCR, /**< Run access register HCCR command */
CTRL_CMD_ACCESS_REG_HTEC, /**< Run access register HTEC command */
CTRL_CMD_ACCESS_REG_HTCR, /**< Run access register HTCR command */
CTRL_CMD_ACCESS_REG_HCPNC, /**< Run access register HCPNC command */
CTRL_CMD_ACCESS_REG_MTPPS, /**< Run access register MTPPS command */
CTRL_CMD_ACCESS_REG_MTPPSE, /**< Run access register MTPPSE command */
CTRL_CMD_ACCESS_REG_MTUTC, /**< Run access register MTUTC command */
CTRL_CMD_ACCESS_REG_MTPPST, /**< Run access register MTPPST command */
CTRL_CMD_ACCESS_REG_MSECQ, /**< Run access register MSECQ command */
CTRL_CMD_ACCESS_REG_MSEES, /**< Run access register MSEES command */
CTRL_CMD_ACCESS_REG_MSPI, /**< Run access register MSPI command */
CTRL_CMD_ACCESS_REG_MCION, /**< Run access register MCION command */
CTRL_CMD_ACCESS_REG_MCFS, /**< Run access register MCFS command */
CTRL_CMD_ACCESS_REG_MDDT, /**< Run access register MDDT command */
CTRL_CMD_ACCESS_REG_MDDQ, /**< Run access register MDDQ command */
CTRL_CMD_ACCESS_REG_MDDC, /**< Run access register MDDC command */
CTRL_CMD_ACCESS_REG_MGPIR, /**< Run access register MGPIR command */
CTRL_CMD_ACCESS_REG_MDFCR, /**< Run access register MDFCR command */
CTRL_CMD_ACCESS_REG_MTECR, /**< Run access register MTECR command */
CTRL_CMD_ACCESS_REG_MTCAP, /**< Run access register MTCAP command */
CTRL_CMD_ACCESS_REG_MTWE, /**< Run access register MTWE command */
CTRL_CMD_ACCESS_REG_MTEWE, /**< Run access register MTEWE command */
CTRL_CMD_ACCESS_REG_MTSDE, /**< Run access register MTSDE command */
CTRL_CMD_ACCESS_REG_MVCAP, /**< Run access register MVCAP command */
CTRL_CMD_ACCESS_REG_MTMP, /**< Run access register MTMP command */
CTRL_CMD_ACCESS_REG_MVCR, /**< Run access register MVCR command */
CTRL_CMD_ACCESS_REG_MCQI, /**< Run access register MCQI command */
CTRL_CMD_ACCESS_REG_MCC, /**< Run access register MCC command */
CTRL_CMD_ACCESS_REG_MCDA, /**< Run access register MCDA command */
CTRL_CMD_ACCESS_REG_MGIR, /**< Run access register MGIR command */
CTRL_CMD_ACCESS_REG_MSGI, /**< Run access register MSGI command */
CTRL_CMD_ACCESS_REG_MDIR, /**< Run access register MDIR command */
CTRL_CMD_ACCESS_REG_MINI, /**< Run access register MINI command */
CTRL_CMD_ACCESS_REG_MCAM, /**< Run access register MCAM command */
CTRL_CMD_ACCESS_REG_MECCC, /**< Run access register MECCC command */
CTRL_CMD_ACCESS_REG_MBCT, /**< Run access register MBCT command */
CTRL_CMD_ACCESS_REG_MTCQ, /**< Run access register MTCQ command */
CTRL_CMD_ACCESS_REG_MTRC_CAP, /**< Run access register MTRC_CAP command */
CTRL_CMD_ACCESS_REG_MTRC_STDB_V2, /**< Run access register MTRC_STDB_V2 command */
CTRL_CMD_ACCESS_REG_MTEIM, /**< Run access register MTEIM command */
CTRL_CMD_ACCESS_REG_MPCIR, /**< Run access register MPCIR command */
CTRL_CMD_ACCESS_REG_MFRC, /**< Run access register MFRC command */
CTRL_CMD_ACCESS_REG_MMCR, /**< Run access register MMCR command */
CTRL_CMD_ACCESS_REG_MFRI, /**< Run access register MFRI command */
CTRL_CMD_ACCESS_REG_MFRP, /**< Run access register MFRP command */
CTRL_CMD_ACCESS_REG_MOGCR, /**< Run access register MOGCR command */
CTRL_CMD_ACCESS_REG_MOLP, /**< Run access register MOLP command */
CTRL_CMD_ACCESS_REG_MPRS, /**< Run access register MPRS command */
CTRL_CMD_ACCESS_REG_MPAT, /**< Run access register MPAT command */
CTRL_CMD_ACCESS_REG_MPAGR, /**< Run access register MPAGR command */
CTRL_CMD_ACCESS_REG_MOMTE, /**< Run access register MOMTE command */
CTRL_CMD_ACCESS_REG_MOCMI, /**< Run access register MOCMI command */
CTRL_CMD_ACCESS_REG_MOCS, /**< Run access register MOCS command */
CTRL_CMD_ACCESS_REG_MAFCR, /**< Run access register MAFCR command */
CTRL_CMD_ACCESS_REG_MAFTI, /**< Run access register MAFTI command */
CTRL_CMD_ACCESS_REG_MAFBI, /**< Run access register MAFBI command */
CTRL_CMD_ACCESS_REG_MAFRI, /**< Run access register MAFRI command */
CTRL_CMD_ACCESS_REG_MOPCE, /**< Run access register MOPCE command */
CTRL_CMD_ACCESS_REG_MOCA, /**< Run access register MOCA command */
CTRL_CMD_ACCESS_REG_MOFRB, /**< Run access register MOFRB command */
CTRL_CMD_ACCESS_REG_MOFPH, /**< Run access register MOFPH command */
CTRL_CMD_ACCESS_REG_MOFPC, /**< Run access register MOFPC command */
CTRL_CMD_ACCESS_REG_MOCBR, /**< Run access register MOCBR command */
CTRL_CMD_ACCESS_REG_MOCBS, /**< Run access register MOCBS command */
CTRL_CMD_ACCESS_REG_MTPSPU, /**< Run access register MTPSPU command */
CTRL_CMD_ACCESS_REG_MTPCPC, /**< Run access register MTPCPC command */
CTRL_CMD_ACCESS_REG_MFGD, /**< Run access register MFGD command */
CTRL_CMD_ACCESS_REG_MODCR, /**< Run access register MODCR command */
CTRL_CMD_ACCESS_REG_MOFS, /**< Run access register MOFS command */
CTRL_CMD_ACCESS_REG_MFDE, /**< Run access register MFDE command */
CTRL_CMD_ACCESS_REG_MDIF, /**< Run access register MDIF command */
CTRL_CMD_ACCESS_REG_MOFRD, /**< Run access register MOFRD command */
CTRL_CMD_ACCESS_REG_IGCR, /**< Run access register IGCR command */
CTRL_CMD_ACCESS_REG_IDDD, /**< Run access register IDDD command */
CTRL_CMD_ACCESS_REG_IEDR, /**< Run access register IEDR command */
CTRL_CMD_ACCESS_REG_IEDS, /**< Run access register IEDS command */
CTRL_CMD_ACCESS_REG_IFBO, /**< Run access register IFBO command */
CTRL_CMD_ACCESS_REG_IICR, /**< Run access register IICR command */
CTRL_CMD_ACCESS_REG_IPAC, /**< Run access register IPAC command */
CTRL_CMD_ACCESS_REG_IHSR, /**< Run access register IHSR command */
CTRL_CMD_ACCESS_REG_IHSCR, /**< Run access register IHSCR command */
CTRL_CMD_ACCESS_REG_IPSR, /**< Run access register IPSR command */
CTRL_CMD_ACCESS_REG_ICSR, /**< Run access register ICSR command */
CTRL_CMD_ACCESS_REG_IPFR, /**< Run access register IPFR command */
CTRL_CMD_ACCESS_REG_ITGCR, /**< Run access register ITGCR command */
CTRL_CMD_ACCESS_REG_ITPR, /**< Run access register ITPR command */
CTRL_CMD_ACCESS_REG_SGCR, /**< Run access register SGCR command */
CTRL_CMD_ACCESS_REG_SPAD, /**< Run access register SPAD command */
CTRL_CMD_ACCESS_REG_SFDB, /**< Run access register SFDB command */
CTRL_CMD_ACCESS_REG_SFDB_V2, /**< Run access register SFDB_V2 command */
CTRL_CMD_ACCESS_REG_SMID_V2, /**< Run access register SMID_V2 command */
CTRL_CMD_ACCESS_REG_SMPU, /**< Run access register SMPU command */
CTRL_CMD_ACCESS_REG_SPMS_V2, /**< Run access register SPMS_V2 command */
CTRL_CMD_ACCESS_REG_SPEVET, /**< Run access register SPEVET command */
CTRL_CMD_ACCESS_REG_SPAFT, /**< Run access register SPAFT command */
CTRL_CMD_ACCESS_REG_SFGC, /**< Run access register SFGC command */
CTRL_CMD_ACCESS_REG_SFTR_V2, /**< Run access register SFTR_V2 command */
CTRL_CMD_ACCESS_REG_SVFA, /**< Run access register SVFA command */
CTRL_CMD_ACCESS_REG_SFDF, /**< Run access register SFDF command */
CTRL_CMD_ACCESS_REG_SFMR, /**< Run access register SFMR command */
CTRL_CMD_ACCESS_REG_SPFSR, /**< Run access register SPFSR command */
CTRL_CMD_ACCESS_REG_SFFP, /**< Run access register SFFP command */
CTRL_CMD_ACCESS_REG_SMPE, /**< Run access register SMPE command */
CTRL_CMD_ACCESS_REG_SMPEB, /**< Run access register SMPEB command */
CTRL_CMD_ACCESS_REG_SLMT, /**< Run access register SLMT command */
CTRL_CMD_ACCESS_REG_SFDT_V2, /**< Run access register SFDT_V2 command */
CTRL_CMD_ACCESS_REG_SFDAT, /**< Run access register SFDAT command */
CTRL_CMD_ACCESS_REG_SPZR, /**< Run access register SPZR command */
CTRL_CMD_ACCESS_REG_IBFMR, /**< Run access register IBFMR command */
CTRL_CMD_ACCESS_REG_IBFMRC, /**< Run access register IBFMRC command */
CTRL_CMD_ACCESS_REG_PTYS, /**< Run access register PTYS command */
CTRL_CMD_ACCESS_REG_PAOS, /**< Run access register PAOS command */
CTRL_CMD_ACCESS_REG_PPCNT, /**< Run access register PPCNT command */
CTRL_CMD_ACCESS_REG_PTSE, /**< Run access register PTSE command */
CTRL_CMD_ACCESS_REG_PTER, /**< Run access register PTER command */
CTRL_CMD_ACCESS_REG_PREI, /**< Run access register PREI command */
CTRL_CMD_ACCESS_REG_PLAR, /**< Run access register PLAR command */
CTRL_CMD_ACCESS_REG_PMAOS, /**< Run access register PMAOS command */
CTRL_CMD_ACCESS_REG_PMTDB, /**< Run access register PMTDB command */
CTRL_CMD_ACCESS_REG_PMECR, /**< Run access register PMECR command */
CTRL_CMD_ACCESS_REG_PMLPE, /**< Run access register PMLPE command */
CTRL_CMD_ACCESS_REG_PMSC, /**< Run access register PMSC command */
CTRL_CMD_ACCESS_REG_PMPE, /**< Run access register PMPE command */
CTRL_CMD_ACCESS_REG_PMMP, /**< Run access register PMMP command */
CTRL_CMD_ACCESS_REG_PMCR, /**< Run access register PMCR command */
CTRL_CMD_ACCESS_REG_PMTPS, /**< Run access register PMTPS command */
CTRL_CMD_ACCESS_REG_PMPT, /**< Run access register PMPT command */
CTRL_CMD_ACCESS_REG_PMPD, /**< Run access register PMPD command */
CTRL_CMD_ACCESS_REG_PMTM, /**< Run access register PMTM command */
CTRL_CMD_ACCESS_REG_PPLR, /**< Run access register PPLR command */
CTRL_CMD_ACCESS_REG_SLTP, /**< Run access register SLTP command */
CTRL_CMD_ACCESS_REG_PTASV2, /**< Run access register PTASV2 command */
CTRL_CMD_ACCESS_REG_SLSIR, /**< Run access register SLSIR command */
CTRL_CMD_ACCESS_REG_PDDR, /**< Run access register PDDR command */
CTRL_CMD_ACCESS_REG_PPTT, /**< Run access register PPTT command */
CTRL_CMD_ACCESS_REG_PPRT, /**< Run access register PPRT command */
CTRL_CMD_ACCESS_REG_PMDR, /**< Run access register PMDR command */
CTRL_CMD_ACCESS_REG_PPHCR, /**< Run access register PPHCR command */
CTRL_CMD_ACCESS_REG_SLLM, /**< Run access register SLLM command */
CTRL_CMD_ACCESS_REG_PPCGP, /**< Run access register PPCGP command */
CTRL_CMD_ACCESS_REG_PCSR, /**< Run access register PCSR command */
CTRL_CMD_ACCESS_REG_PMTU, /**< Run access register PMTU command */
CTRL_CMD_ACCESS_REG_PPAD, /**< Run access register PPAD command */
CTRL_CMD_ACCESS_REG_PIFR_V2, /**< Run access register PIFR_V2 command */
CTRL_CMD_ACCESS_REG_PBSR, /**< Run access register PBSR command */
CTRL_CMD_ACCESS_REG_PLLP, /**< Run access register PLLP command */
CTRL_CMD_ACCESS_REG_PPCR, /**< Run access register PPCR command */
CTRL_CMD_ACCESS_REG_PLDT, /**< Run access register PLDT command */
CTRL_CMD_ACCESS_REG_PLDC, /**< Run access register PLDC command */
CTRL_CMD_ACCESS_REG_PLIBDB, /**< Run access register PLIBDB command */
CTRL_CMD_ACCESS_REG_PBGCR, /**< Run access register PBGCR command */
CTRL_CMD_ACCESS_REG_PPIR, /**< Run access register PPIR command */
CTRL_CMD_ACCESS_REG_PHBR, /**< Run access register PHBR command */
CTRL_CMD_ACCESS_REG_PHRR, /**< Run access register PHRR command */
CTRL_CMD_ACCESS_REG_PBWC, /**< Run access register PBWC command */
CTRL_CMD_ACCESS_REG_PBWR, /**< Run access register PBWR command */
CTRL_CMD_ACCESS_REG_SBGCR, /**< Run access register SBGCR command */
CTRL_CMD_ACCESS_REG_SBSRD, /**< Run access register SBSRD command */
CTRL_CMD_ACCESS_REG_SBHBR_V2, /**< Run access register SBHBR_V2 command */
CTRL_CMD_ACCESS_REG_SBHRR_V2, /**< Run access register SBHRR_V2 command */
CTRL_CMD_ACCESS_REG_SBCTR, /**< Run access register SBCTR command */
CTRL_CMD_ACCESS_REG_SBHPC, /**< Run access register SBHPC command */
CTRL_CMD_ACCESS_REG_SBSNT, /**< Run access register SBSNT command */
CTRL_CMD_ACCESS_REG_SBSNS, /**< Run access register SBSNS command */
CTRL_CMD_ACCESS_REG_SBSNTE, /**< Run access register SBSNTE command */
CTRL_CMD_ACCESS_REG_PGCR, /**< Run access register PGCR command */
CTRL_CMD_ACCESS_REG_PPBT, /**< Run access register PPBT command */
CTRL_CMD_ACCESS_REG_PEVPB, /**< Run access register PEVPB command */
CTRL_CMD_ACCESS_REG_PVGT, /**< Run access register PVGT command */
CTRL_CMD_ACCESS_REG_PVBT, /**< Run access register PVBT command */
CTRL_CMD_ACCESS_REG_PEMRBT, /**< Run access register PEMRBT command */
CTRL_CMD_ACCESS_REG_PERB, /**< Run access register PERB command */
CTRL_CMD_ACCESS_REG_PERBRG, /**< Run access register PERBRG command */
CTRL_CMD_ACCESS_REG_PERBEG, /**< Run access register PERBEG command */
CTRL_CMD_ACCESS_REG_PERLA, /**< Run access register PERLA command */
CTRL_CMD_ACCESS_REG_PERAR, /**< Run access register PERAR command */
CTRL_CMD_ACCESS_REG_PEFAAD, /**< Run access register PEFAAD command */
CTRL_CMD_ACCESS_REG_PPRR, /**< Run access register PPRR command */
CTRL_CMD_ACCESS_REG_PPBS, /**< Run access register PPBS command */
CTRL_CMD_ACCESS_REG_PEAPS, /**< Run access register PEAPS command */
CTRL_CMD_ACCESS_REG_PECNRE, /**< Run access register PECNRE command */
CTRL_CMD_ACCESS_REG_PECNRR, /**< Run access register PECNRR command */
CTRL_CMD_ACCESS_REG_PECNEE, /**< Run access register PECNEE command */
CTRL_CMD_ACCESS_REG_PECNER, /**< Run access register PECNER command */
CTRL_CMD_ACCESS_REG_QCAP, /**< Run access register QCAP command */
CTRL_CMD_ACCESS_REG_QEEC, /**< Run access register QEEC command */
CTRL_CMD_ACCESS_REG_QTCT, /**< Run access register QTCT command */
CTRL_CMD_ACCESS_REG_QTCTM, /**< Run access register QTCTM command */
CTRL_CMD_ACCESS_REG_QSPTC, /**< Run access register QSPTC command */
CTRL_CMD_ACCESS_REG_QSTCT, /**< Run access register QSTCT command */
CTRL_CMD_ACCESS_REG_QSPIP, /**< Run access register QSPIP command */
CTRL_CMD_ACCESS_REG_QSPCP, /**< Run access register QSPCP command */
CTRL_CMD_ACCESS_REG_QTTTL, /**< Run access register QTTTL command */
CTRL_CMD_ACCESS_REG_QTQCR, /**< Run access register QTQCR command */
CTRL_CMD_ACCESS_REG_QTQDR, /**< Run access register QTQDR command */
CTRL_CMD_ACCESS_REG_QTEEM, /**< Run access register QTEEM command */
CTRL_CMD_ACCESS_REG_QTDEM, /**< Run access register QTDEM command */
CTRL_CMD_ACCESS_REG_QPDPC, /**< Run access register QPDPC command */
CTRL_CMD_ACCESS_REG_QSLL, /**< Run access register QSLL command */
CTRL_CMD_ACCESS_REG_QPTG, /**< Run access register QPTG command */
CTRL_CMD_ACCESS_REG_QTGTC, /**< Run access register QTGTC command */
CTRL_CMD_ACCESS_REG_CPQE, /**< Run access register CPQE command */
CTRL_CMD_ACCESS_REG_CHLTR, /**< Run access register CHLTR command */
CTRL_CMD_ACCESS_REG_CHLTM, /**< Run access register CHLTM command */
CTRL_CMD_ACCESS_REG_CHLMM, /**< Run access register CHLMM command */
CTRL_CMD_ACCESS_REG_CEGCR, /**< Run access register CEGCR command */
CTRL_CMD_ACCESS_REG_CEPC, /**< Run access register CEPC command */
CTRL_CMD_ACCESS_REG_CEDR, /**< Run access register CEDR command */
CTRL_CMD_ACCESS_REG_CEER, /**< Run access register CEER command */
CTRL_CMD_ACCESS_REG_CWGCR, /**< Run access register CWGCR command */
CTRL_CMD_ACCESS_REG_CWTPM, /**< Run access register CWTPM command */
CTRL_CMD_ACCESS_REG_RIGR_V2, /**< Run access register RIGR_V2 command */
CTRL_CMD_ACCESS_REG_RATRB, /**< Run access register RATRB command */
CTRL_CMD_ACCESS_REG_RTDP, /**< Run access register RTDP command */
CTRL_CMD_ACCESS_REG_RIPS, /**< Run access register RIPS command */
CTRL_CMD_ACCESS_REG_RALTA, /**< Run access register RALTA command */
CTRL_CMD_ACCESS_REG_RALST, /**< Run access register RALST command */
CTRL_CMD_ACCESS_REG_RALTB, /**< Run access register RALTB command */
CTRL_CMD_ACCESS_REG_RALEU, /**< Run access register RALEU command */
CTRL_CMD_ACCESS_REG_RALCM, /**< Run access register RALCM command */
CTRL_CMD_ACCESS_REG_RMID_V2, /**< Run access register RMID_V2 command */
CTRL_CMD_ACCESS_REG_RMPE, /**< Run access register RMPE command */
CTRL_CMD_ACCESS_REG_REIV, /**< Run access register REIV command */
CTRL_CMD_ACCESS_REG_RNGCR, /**< Run access register RNGCR command */
CTRL_CMD_ACCESS_REG_RXLTE, /**< Run access register RXLTE command */
CTRL_CMD_ACCESS_REG_RXLTM, /**< Run access register RXLTM command */
CTRL_CMD_ACCESS_REG_RXLTCC, /**< Run access register RXLTCC command */
CTRL_CMD_ACCESS_REG_RLCME, /**< Run access register RLCME command */
CTRL_CMD_ACCESS_REG_RLCMLE, /**< Run access register RLCMLE command */
CTRL_CMD_ACCESS_REG_RLCMLD, /**< Run access register RLCMLD command */
CTRL_CMD_ACCESS_REG_RARGCR, /**< Run access register RARGCR command */
CTRL_CMD_ACCESS_REG_RARPC, /**< Run access register RARPC command */
CTRL_CMD_ACCESS_REG_RARSR, /**< Run access register RARSR command */
CTRL_CMD_ACCESS_REG_RARPR, /**< Run access register RARPR command */
CTRL_CMD_ACCESS_REG_RARCL, /**< Run access register RARCL command */
CTRL_CMD_ACCESS_REG_RARPPM, /**< Run access register RARPPM command */
CTRL_CMD_ACCESS_REG_RARLU, /**< Run access register RARLU command */
CTRL_CMD_ACCESS_REG_RARFT, /**< Run access register RARFT command */
CTRL_CMD_ACCESS_REG_RARFTB, /**< Run access register RARFTB command */
CTRL_CMD_ACCESS_REG_RARLPGT, /**< Run access register RARLPGT command */
CTRL_CMD_ACCESS_REG_RARCC, /**< Run access register RARCC command */
CTRL_CMD_ACCESS_REG_RSNH, /**< Run access register RSNH command */
CTRL_CMD_ACCESS_REG_RIRT, /**< Run access register RIRT command */
CTRL_CMD_ACCESS_REG_MPNHLFE, /**< Run access register MPNHLFE command */
CTRL_CMD_ACCESS_REG_TNQCR, /**< Run access register TNQCR command */
CTRL_CMD_ACCESS_REG_TNPC, /**< Run access register TNPC command */
CTRL_CMD_ACCESS_REG_TNGEE, /**< Run access register TNGEE command */
CTRL_CMD_ACCESS_REG_TNCR, /**< Run access register TNCR command */
CTRL_CMD_ACCESS_REG_TNCR_V2, /**< Run access register TNCR_V2 command */
CTRL_CMD_ACCESS_REG_TNUMT, /**< Run access register TNUMT command */
CTRL_CMD_ACCESS_REG_TNGCR, /**< Run access register TNGCR command */
CTRL_CMD_ACCESS_REG_TNQDR, /**< Run access register TNQDR command */
CTRL_CMD_ACCESS_REG_TNEEM, /**< Run access register TNEEM command */
CTRL_CMD_ACCESS_REG_TNDEM, /**< Run access register TNDEM command */
CTRL_CMD_ACCESS_REG_TNIFR, /**< Run access register TNIFR command */
CTRL_CMD_ACCESS_REG_TNIFR_V2, /**< Run access register TNIFR_V2 command */
CTRL_CMD_ACCESS_REG_TIGCR, /**< Run access register TIGCR command */
CTRL_CMD_ACCESS_REG_TIQCR, /**< Run access register TIQCR command */
CTRL_CMD_ACCESS_REG_TIQDR, /**< Run access register TIQDR command */
CTRL_CMD_ACCESS_REG_TIEEM, /**< Run access register TIEEM command */
CTRL_CMD_ACCESS_REG_TIDEM, /**< Run access register TIDEM command */
CTRL_CMD_ACCESS_REG_FGCR, /**< Run access register FGCR command */
CTRL_CMD_ACCESS_REG_FPUMS, /**< Run access register FPUMS command */
CTRL_CMD_ACCESS_REG_FPHHC, /**< Run access register FPHHC command */
CTRL_CMD_ACCESS_REG_FPPC, /**< Run access register FPPC command */
CTRL_CMD_ACCESS_REG_FPFTT, /**< Run access register FPFTT command */
CTRL_CMD_ACCESS_REG_FPHTT, /**< Run access register FPHTT command */
CTRL_CMD_ACCESS_REG_FPTS, /**< Run access register FPTS command */
CTRL_CMD_ACCESS_REG_FMQC, /**< Run access register FMQC command */
CTRL_CMD_ACCESS_REG_FMTPC, /**< Run access register FMTPC command */
CTRL_CMD_ACCESS_REG_FMTPA, /**< Run access register FMTPA command */
CTRL_CMD_ACCESS_REG_FMTB, /**< Run access register FMTB command */
CTRL_CMD_ACCESS_REG_FMTC, /**< Run access register FMTC command */
CTRL_CMD_ACCESS_REG_FMTE, /**< Run access register FMTE command */
CTRL_CMD_ACCESS_REG_FMTM, /**< Run access register FMTM command */
CTRL_CMD_ACCESS_REG_FMEP, /**< Run access register FMEP command */
CTRL_CMD_ACCESS_REG_FSGCR, /**< Run access register FSGCR command */
CTRL_CMD_ACCESS_REG_FSDB, /**< Run access register FSDB command */
CTRL_CMD_ACCESS_REG_FSPT, /**< Run access register FSPT command */
CTRL_CMD_ACCESS_REG_FSDC, /**< Run access register FSDC command */
CTRL_CMD_ACCESS_REG_FSPS, /**< Run access register FSPS command */
CTRL_CMD_ACCESS_REG_FSTM, /**< Run access register FSTM command */
CTRL_CMD_ACCESS_REG_FSED, /**< Run access register FSED command */
CTRL_CMD_ACCESS_REG_FSHE, /**< Run access register FSHE command */
CTRL_CMD_ACCESS_REG_FSFH, /**< Run access register FSFH command */
CTRL_CMD_ACCESS_REG_XGCR, /**< Run access register XGCR command */
CTRL_CMD_ACCESS_REG_XLTQ, /**< Run access register XLTQ command */
CTRL_CMD_ACCESS_REG_XMDR, /**< Run access register XMDR command */
CTRL_CMD_ACCESS_REG_XLKBU, /**< Run access register XLKBU command */
CTRL_CMD_ACCESS_REG_XRMT, /**< Run access register XRMT command */
CTRL_CMD_ACCESS_REG_XRALTA, /**< Run access register XRALTA command */
CTRL_CMD_ACCESS_REG_XRALST, /**< Run access register XRALST command */
CTRL_CMD_ACCESS_REG_XRALTB, /**< Run access register XRALTB command */
CTRL_CMD_ACCESS_REG_UGCAP, /**< Run access register UGCAP command */
CTRL_CMD_ACCESS_REG_UPCAP, /**< Run access register UPCAP command */
CTRL_CMD_ACCESS_REG_UGCR, /**< Run access register UGCR command */
CTRL_CMD_ACCESS_REG_UPCON, /**< Run access register UPCON command */
CTRL_CMD_ACCESS_REG_UMTU, /**< Run access register UMTU command */
CTRL_CMD_ACCESS_REG_UVER, /**< Run access register UVER command */
CTRL_CMD_ACCESS_REG_UPVC, /**< Run access register UPVC command */
CTRL_CMD_ACCESS_REG_UPAFT, /**< Run access register UPAFT command */
CTRL_CMD_ACCESS_REG_UTAR, /**< Run access register UTAR command */
CTRL_CMD_ACCESS_REG_UPBT, /**< Run access register UPBT command */
CTRL_CMD_ACCESS_REG_UTCE, /**< Run access register UTCE command */
CTRL_CMD_ACCESS_REG_URCR, /**< Run access register URCR command */
CTRL_CMD_ACCESS_REG_USADB, /**< Run access register USADB command */
CTRL_CMD_ACCESS_REG_USAK, /**< Run access register USAK command */
CTRL_CMD_ACCESS_REG_USACN, /**< Run access register USACN command */
CTRL_CMD_ACCESS_REG_UTCC, /**< Run access register UTCC command */
CTRL_CMD_ACCESS_REG_UPCNT, /**< Run access register UPCNT command */
CTRL_CMD_ACCESS_REG_UCCR, /**< Run access register UCCR command */
CTRL_CMD_ACCESS_REG_UTFD, /**< Run access register UTFD command */
CTRL_CMD_ACCESS_REG_UTFC, /**< Run access register UTFC command */
CTRL_CMD_ACCESS_REG_UTER, /**< Run access register UTER command */
