/*
* Copyright (c) 2010-2018,  Mellanox Technologies. All rights reserve
*
* This software is available to you under a choice of one of two
* licenses.  You may choose to be licensed under the terms of the GNU
* General Public License (GPL) Version 2, available from the file
* COPYING in the main directory of this source tree, or the
* OpenIB.org BSD license below:
*
*     Redistribution and use in source and binary forms, with or
*     without modification, are permitted provided that the following
*     conditions are met:
*
*      - Redistributions of source code must retain the above
*        copyright notice, this list of conditions and the following
*        disclaimer.
*
*      - Redistributions in binary form must reproduce the above
*        copyright notice, this list of conditions and the following
*        disclaimer in the documentation and/or other materials
*        provided with the distribution.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
* NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
* BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
* ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
* CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
* SOFTWARE.
*/

/*
 * THIS FILE IS AUTO GENERATED.
 * DO NOT MAKE ANY CHANGES!
 * They will be erased with next update.
 *
 * Date: 2019-08-05 14:12
 * ADABE PRM Version: Rev 1.55.004
 * Generated by adb_to_sxd.py (A-ME Version: a-me-1.0.123_2019-08-04)
 *
 */

CTRL_CMD_ACCESS_REG_PECNRR, /**< Run access register PECNRR command */
CTRL_CMD_ACCESS_REG_PAOS, /**< Run access register PAOS command */
CTRL_CMD_ACCESS_REG_MTUTC, /**< Run access register MTUTC command */
CTRL_CMD_ACCESS_REG_SFMR, /**< Run access register SFMR command */
CTRL_CMD_ACCESS_REG_RIPS, /**< Run access register RIPS command */
CTRL_CMD_ACCESS_REG_TNPC, /**< Run access register TNPC command */
CTRL_CMD_ACCESS_REG_PECNRE, /**< Run access register PECNRE command */
CTRL_CMD_ACCESS_REG_PEMRBT, /**< Run access register PEMRBT command */
CTRL_CMD_ACCESS_REG_MPCIR, /**< Run access register MPCIR command */
CTRL_CMD_ACCESS_REG_RALCM, /**< Run access register RALCM command */
CTRL_CMD_ACCESS_REG_RMPE, /**< Run access register RMPE command */
CTRL_CMD_ACCESS_REG_PECNEE, /**< Run access register PECNEE command */
CTRL_CMD_ACCESS_REG_MDFCR, /**< Run access register MDFCR command */
CTRL_CMD_ACCESS_REG_SMPEB, /**< Run access register SMPEB command */
CTRL_CMD_ACCESS_REG_PEVPB, /**< Run access register PEVPB command */
CTRL_CMD_ACCESS_REG_MTMP, /**< Run access register MTMP command */
CTRL_CMD_ACCESS_REG_IBFMR, /**< Run access register IBFMR command */
CTRL_CMD_ACCESS_REG_TNCR_V2, /**< Run access register TNCR_V2 command */
CTRL_CMD_ACCESS_REG_PPBS, /**< Run access register PPBS command */
CTRL_CMD_ACCESS_REG_RTDP, /**< Run access register RTDP command */
CTRL_CMD_ACCESS_REG_PECNER, /**< Run access register PECNER command */
CTRL_CMD_ACCESS_REG_IICR, /**< Run access register IICR command */
CTRL_CMD_ACCESS_REG_IBFMRC, /**< Run access register IBFMRC command */
CTRL_CMD_ACCESS_REG_PEAPS, /**< Run access register PEAPS command */
CTRL_CMD_ACCESS_REG_IDDD, /**< Run access register IDDD command */
CTRL_CMD_ACCESS_REG_IEDR, /**< Run access register IEDR command */
CTRL_CMD_ACCESS_REG_IEDS, /**< Run access register IEDS command */
CTRL_CMD_ACCESS_REG_TNQCR, /**< Run access register TNQCR command */
CTRL_CMD_ACCESS_REG_MPAGR, /**< Run access register MPAGR command */
CTRL_CMD_ACCESS_REG_SBHRR_V2, /**< Run access register SBHRR_V2 command */
CTRL_CMD_ACCESS_REG_HMON, /**< Run access register HMON command */
CTRL_CMD_ACCESS_REG_MGPIR, /**< Run access register MGPIR command */
CTRL_CMD_ACCESS_REG_PEFAAD, /**< Run access register PEFAAD command */
CTRL_CMD_ACCESS_REG_MOMTE, /**< Run access register MOMTE command */
CTRL_CMD_ACCESS_REG_REIV, /**< Run access register REIV command */
CTRL_CMD_ACCESS_REG_SVFA, /**< Run access register SVFA command */
CTRL_CMD_ACCESS_REG_SMPE, /**< Run access register SMPE command */
CTRL_CMD_ACCESS_REG_MCC, /**< Run access register MCC command */
CTRL_CMD_ACCESS_REG_SFDB, /**< Run access register SFDB command */
CTRL_CMD_ACCESS_REG_MCDA, /**< Run access register MCDA command */
CTRL_CMD_ACCESS_REG_SFGC, /**< Run access register SFGC command */
CTRL_CMD_ACCESS_REG_SBHBR_V2, /**< Run access register SBHBR_V2 command */
CTRL_CMD_ACCESS_REG_MCQI, /**< Run access register MCQI command */
CTRL_CMD_ACCESS_REG_PMTPS, /**< Run access register PMTPS command */
